### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SuperAdam47** [NightRich/PlayAndWin#1]
![screenshot_20180607-032654](https://user-images.githubusercontent.com/16169771/41071904-5c7e9b50-6a03-11e8-997d-fc8ce6e85bbf.png)

**Comment by NightRich** [comment]
Eklentiyi dün v1.4 sürümüne yükselttim. 1.4 Task API değişti. 1.4 dışındaki sürümlerde çalışmaz eklenti.

**Comment by SuperAdam47** [comment]
zaten 1.4

**Comment by NightRich** [comment]
Hangi yazılımı kullanıyorsun

**Comment by SuperAdam47** [comment]
altay

**Comment by NightRich** [comment]
Altay 1.7 kullan ben 1.7'de denedim sorun yok.

**Comment by SuperAdam47** [comment]
1.7 ne IQ

**Comment by NightRich** [comment]
Altay son versiyon kullan, yada pm-mp kullan ikisindede çalışıyor...
